language: php

php:
  - 8.1
  - 8.2
  - 8.3
  - 8.4
env:
  global:
    - setup=basic

sudo: false

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - >
    XDEBUG_MODE=coverage vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

matrix:
  fast_finish: true

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="9857f9bb4b1c260b94eb773a541d6e42e05db0db45d5a25757590276d5e50445" --format=php-clover coverage.clover

notifications:
  slack: big-boss-studio:vLrsJ3hpqgIYugU7IKLMUwj2
